### ISSUE TITLE
CSFR token error

### ISSUE THREAD

**Issue by mar005** [simse/pyunraid#2]
Hi, 

I am running this using virtualenv on my Mac using the python 3.7 interpreter, and I get this error using the same code.

`Traceback (most recent call last):
  File "unraid.py", line 4, in <module>
    unraid = Unraid('192.168.2.59', 'root', '[REDACTED]')
  File "/Users/miguel/Documents/Python/UnRAID/venv/lib/python3.7/site-packages/pyunraid/unraid.py", line 35, in __init__
    self.csfr_token = get_csfr_token(url, username, password)
  File "/Users/miguel/Documents/Python/UnRAID/venv/lib/python3.7/site-packages/pyunraid/helpers.py", line 18, in get_csfr_token
    csfr_token = search.group(2)
AttributeError: 'NoneType' object has no attribute 'group'`

how do I fix this?

**Comment by simse** [comment]
Are you running the latest version of Unraid?

**Comment by mar005** [comment]
Yes I am. Wondering if that is what is the issue.

**Comment by simse** [comment]
Yep that would be it. `pyunraid` only supports 6.7.x right now. I have not updated my own server yet, so I can't update this yet. Sorry about that.
